### ISSUE TITLE
Volcano Plot "negative values in input"

### ISSUE THREAD

**Issue by MLKaufman** [biolab/orange3-bioinformatics#1]
##### Orange version
Orange version 3.4 to 3.9

##### Expected behavior
Plot Volcano Plot

##### Actual behavior
Using the caffeine data set from the volcano plot example... error reads "negative values in input".  This happens no matter what using any data set from GEO. Or if I provide my own. Even if I get read of all negatives in dataset.

##### Steps to reproduce the behavior
Run the example Geo Data set from example documentation.

**Comment by JakaKokosar** [comment]
Hi, sorry for late answer. Volcano Plot is not supported in orange3-bioinformatics (version 3.0.0 and forward).

Please refer to the [old repository](https://github.com/biolab/orange-bio), if still relevant.
