### ISSUE TITLE
Cluster Analysis: enhancements

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-bioinformatics#105]
##### Bioinformatics version
3.2.6

##### Expected behavior
The following enhancements would greatly improve scOrange:

- Commit/send functionality (default: off). Do not start the computation before user checks all the parameters.
- Progress goes beyond 100% if you change cluster variable.
- Remember settings *and* outputs when workflow is re-opened.
- Output more terms than 5 (but keep max. display to 5).
- Output 'Gene Scores' is missing table metadata to use genes in e.g. Score Cells.

Thanks!

**Comment by ajdapretnar** [comment]
Can I add that widget is huge and you will have trouble showing it on older projectors. Consider making it smaller.

**Comment by mstrazar** [comment]
This is a trade-off we were prepared to take, as it is meant to display a concise, yet comprehensive results summary on a single view.
