### ISSUE TITLE
GEO Data Sets in pickled format

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#108]
GEO DataSets are, I assume, transferred from the server in the .soft format. While they load reasonably fast, it takes a while for Orange to locally transform them into a tab-delimited format and to local Orange's presentation. Downloading these data sets in GEO Data Sets widget could be substantially faster if this conversion would be performed on the server, and the data would be stored at the server in the pickled format.

**Comment by JakaKokosar** [comment]
Currently, the data is hosted on [this FTP server](https://ftp.ncbi.nih.gov/). If we proceed with this, we would need to host the data on our servers.

**Comment by BlazZupan** [comment]
Jaka, you are right. We would host the preprocessed data on our file server. Could be the same server as we are hosting all other data sets for bioinformatics add-on. Of course, we would not include these files in the list shown in the Databases Update.

**Comment by BlazZupan** [comment]
This issue is not trivial, as the server would need to separate gene expression data and meta information on sample annotations. This should though not be too complex, and if properly designed, it should substantially speed-up the loading and management of the data in GEO Data Sets widget, which is currently slow as it starts with parsing of the text files.
