### ISSUE TITLE
GO Browser widget too large

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#115]
The default size of GO Browser is fine, but cannot be reduced. The minimum size specified is too large. Specially for the purposes of screenshots, the widget could be much smaller.

**Comment by JakaKokosar** [comment]
I labelled this as a discussion. I think it would be wise to plan a new interface for this widget. The current state of GUI controls is far from optimal and prevents the widget from decreasing height.

**Comment by JakaKokosar** [comment]
Also, #2 could be an interesting way of improving the performance of this widget.

**Comment by ajdapretnar** [comment]
For one, evidence codes in annotation could be designed the way Select Rows implement 'is one of' option.

**Comment by JakaKokosar** [comment]
I also mean in terms of usability. Are all of the controls actually needed? What I mean is that we don't have any insight into who and how uses this widget (or even this add-on). My suggestion is that we start small and simplify controls. We can always add advanced controls when and if they are even needed.

**Comment by BlazZupan** [comment]
New version of Orange allows resizing of widgets not limiting them to the size where all the controls would be visible.
