### ISSUE TITLE
[ENH] Improve interface of Marker Genes widget

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-bioinformatics#132]
I suggest to improve maker genes widget with introducing grouping: Make an option to group marker genes based on e.g. Cell Type to improve the readability.

**Comment by PrimozGodec** [comment]
I moved part of this issue in new one https://github.com/biolab/orange3-bioinformatics/issues/158 and updated the issue text. This issue still needs some discussion. Current options are:

- to extend current widget with a checkbox which would merge genes based on cell types. 
- propose new `Cell Types` widget which would have a table grouped by cell types.

**Comment by JakaKokosar** [comment]
Closing this issue. 
Further discussions about interface of marker genes widget can be found [in this issue.](https://github.com/biolab/orange3-bioinformatics/issues/180)
