### ISSUE TITLE
Annotator: t-SNE variables implemented via ComputeValue

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-bioinformatics#149]
Annotator widget computes the t-SNE projection and stores in it normal Orange variables. Use the ComputeValue class so that the t-SNE-x and t-SNE-y variables can be computed on new data, e.g. using _Apply Domain_. This is how the original _t-SNE_ widget works.

**Comment by JakaKokosar** [comment]
What is the status on this? (@PrimozGodec, @mstrazar )?

**Comment by PrimozGodec** [comment]
It was fixed in https://github.com/biolab/orange3-bioinformatics/pull/165 now the t-SNE projection is computed with tSNE widget.
