### ISSUE TITLE
pip install fails on windows

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-bioinformatics#152]
#134 introduced Shapely as new requirement. This is the reason that pip install orange3-bioinformatics fails on windows.

info:
https://github.com/Toblerity/Shapely/issues/367

**Comment by PrimozGodec** [comment]
I am sorry that I didn't notice that before. So it seems that we will need to find a way to avoid using Shapely.

**Comment by flutefreak7** [comment]
The other unfortunate options are to provide instructions to either install Shapely using a wheel from Gohlke's site or to have Windows users install GEOS and add the folder with the GEOS DLLs to their path. I realize neither of those likely works in CI.

There might even be a 3rd option involving downloading the shapely conda-forge package and extracting the DLLs from there.

I agree that the best solution is to just get Shapely's wheels working correctly.

**Comment by PrimozGodec** [comment]
Hm. Here we have a problem that Orange3-bioinformatics is an Orange add-on which is installed by users through the user interface. Our users are mainly not capable of installing it manually.

**Comment by mwtoews** [comment]
FYI, Windows binary wheels are finally available on PyPI.
```
pip install shapely>=1.7.0
```
