### ISSUE TITLE
Replicated entries in Marker Genes

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#157]
##### Single Cell version
0.9.1

##### Expected behavior
Each marker gene for a particular organism should be listed only once.

##### Actual behavior
Marker genes are repeated, each time with repeated reference. See, for instance CD14 and S100A9 in the screenshot below.

![screen shot 2019-02-22 at 11 30 31](https://user-images.githubusercontent.com/726604/53236764-5a07d300-3695-11e9-9ccf-b73401a50c11.png)

##### Suggested changes
We would like to maintain the links to the reference. Could it be that in one cell there are two separate links? Or should we have a primary and secondary reference?

**Comment by JakaKokosar** [comment]
Since the redesign of this widget, the unique gene entries are a pair of Entrez ID and Cell type.

![Screenshot 2019-07-04 at 09 55 48](https://user-images.githubusercontent.com/15876321/60649302-0b87f380-9e42-11e9-97d8-da935c8a6747.png)

Is this issue still relevant?
