### ISSUE TITLE
[ENH] Number of selected marker genes and clear selection in marker genes widget

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-bioinformatics#158]
Marker genes widget does not have an easy option to deselect all marker genes. Today at the meeting we have talked about button `Clear selection` which will be placed below the table. 

Also, there would be nice to have information about a number of all genes and the number of selected genes in the status bar - bottom of the widget.

**Comment by NejcDebevec** [comment]
@PrimozGodec I will wait with this issue, because there is new design for Marker Genes in plan #180.

**Comment by JakaKokosar** [comment]
Closing this issue. 
Further discussions about interface of marker genes widget can be found [in this issue.](https://github.com/biolab/orange3-bioinformatics/issues/180)
