### ISSUE TITLE
Annotator: map new data set

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#159]
##### Motivation

Annotator takes a data set and set of labeled genes and annotates clusters of data instances (e.g. cells) with corresponding gene group labels. We can use the resulting embedder and annotation scaffold to map and classify new data instances.

##### Proposed changes

1. Remove "Data Subset" input channel
2. Rename "Data" channel to "Reference Data"
3. Add "Secondary Data" input channel (should appear after "Reference Data"
4. In the options, add checkbox "Show Reference Data" (default checked). Unchecking this option hides the reference data points.

When the widget is presented the Secondary Data, the reference data, if displayed, is grayed out and moved to the background. Secondary data is displayed on the top. Any selection is canceled. The new selection applies only to the Secondary Data. The output ("Data") contains both data sets, merged, with a colon "Data Source" that provides the name of the data set as assigned to the DataTable object.

Extension: Secondary Data channel supports multiple inputs.

**Comment by mstrazar** [comment]
Minor: when taxonomy ID is different in Data and Genes, raise warning and only show the t-SNE projection. This is a common mistake with current Marker Genes widget.

Warning text: "Data and Genes appear to describe different organisms (mismatching Taxonomy IDs.)"

![annotator-organism-mismatch](https://user-images.githubusercontent.com/5073833/61035533-a004cf80-a3c7-11e9-83f7-9d6cf4bfd05c.png)

**Comment by JakaKokosar** [comment]
@VesnaT, can we close this?
