### ISSUE TITLE
GEO Data Sets: row sorting treats numbers as strings

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#174]
##### Expected behavior

Sorting the rows in GEO Data Sets should consider Samples, Features, Genes, or Subsets as numbers. When sorting by Samples, for instance, the largest data set should be GDS3268 with 202 samples.

##### Actual behavior

Sorting rows in GEO Data Sets widgets by Samples, Features, Genes, or Subsets treats numbers as strings and hence does not work properly.
![image](https://user-images.githubusercontent.com/726604/61997360-d0738b80-b0a0-11e9-83a1-c1894f06a2f1.png)

##### Steps to reproduce the behavior

Open GEO Data Sets widget and sort by any of the mentioned fields.

**Comment by ajdapretnar** [comment]
This is not the only widget with such an issue. I assume most TableView widgets behave in the same way.
https://github.com/biolab/orange3/issues/3947
