### ISSUE TITLE
Gene Set Enrichment should include marker genes

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#176]
##### Expected behavior

Gene Set Enrichment widget should, among other, also include gene groups from marker genes data bases.

##### Actual behavior

Currently, only KEGG and GO are included.

![image](https://user-images.githubusercontent.com/726604/61998122-762bf800-b0ab-11e9-94b9-f71093771eb1.png)

**Comment by JakaKokosar** [comment]
Workaround until we add new gene sets, gene set widget knows how to handle custom gene sets data.

<img width="1510" alt="Screenshot 2019-07-30 at 09 38 12" src="https://user-images.githubusercontent.com/15876321/62110219-3c770f00-b2ae-11e9-9ede-f0249c42b2ef.png">

**Comment by JakaKokosar** [comment]
Marker genes are included in gene sets library (https://github.com/JakaKokosar/bioinformatics-serverfiles/commit/554821ab5bb3b3d9fbf4c86915c7f275d7c43947). Closing.
