### ISSUE TITLE
Marker genes redesign

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3-bioinformatics#180]
As discussed, the "Marker Genes" isn't the most user-friendly widget to use because it's hard to see what's selected. I propose a design more similar to "Select Columns", which will make it a lot easier to see which genes are already selected.

![image](https://user-images.githubusercontent.com/5758119/62474501-4f547c80-b7a3-11e9-8af9-0356ae7eb136.png)

The widget would now have two selection areas with lists of marker genes, with the selected ones going to the right, "Selected" area and the remaining unselected ones would be in the left, "Available" section. Once a gene is selected, it's removed from the left list and goes to the right area.

Filtering should work both by cell-type and by marker name (so I should be able to search both using "Monocyte" for cell-type and "SST" as a marker.

Additionally, (this would probably be more work, and should be treated as secondary), we'd want some kind of grouping for marker genes by cell type. We might have one level containing cell types, which can then be expanded to reveal their corresponding marker genes, as indicated by the "+" and "-" signs in the sketch. This would be the same in both the "Available" and "Selected" sections of the widget. The ordering of the cell types should be the same in both panels, but in the "Selected" section, only cell types with a selected gene should appear. In the "Available" section, the cell type should always be visible, even if we've selected all the markers for that cell-type. It would be confusing if a cell-type disappeared from the "Available" if we've selected all the markers.

**Comment by PrimozGodec** [comment]
Should we keep the current look two selection area (with all current columns)?
![Screenshot 2019-11-19 12 05 45](https://user-images.githubusercontent.com/6421558/69141397-fcd66c00-0ac4-11ea-95ad-e525a9cf2419.png)

Or should we shrink the view? What information should we include in a view? 
If we will have groups (cell types) this column is not required anymore, also we can join the gene name and Entrez id. Is the reference column required?
The view I suggest is:

```
Cell type 1
   Gene 1 (Entrez ID 1) 
   Gene 2 (Entrez ID 2) 
Cell type 2
   Gene 3 (Entrez ID 3)
....
```

In this view, I didn't include **function** column but probably we want to keep this one? If we do not reduce the number of columns the widget would be IMO to wide since both selection areas would have all columns. What do you think @pavlin-policar and @BlazZupan?

**Comment by pavlin-policar** [comment]
So, I agree, keeping all the columns will make each selection area too wide, so clearly, we're going to have to hide some information. I don't think the Entrez ID is a very useful thing to show here, but with that in mind, we should definitely be able to search by Entrez ID, and also by Ensembl ID. So while I wouldn't show these IDs in the default views, it should be searchable. 

The next issue is the "function" column. This is too wide. But it's also a good thing to have somewhere... So I have two ideas here, which might both come in useful.
1. We could have a dropdown somewhere in the interface which would determine the grouping of genes. For instance, instead of grouping by "Cell type", we might group by "function" or "organ".
2. Add a gene information panel to the right side of the widget. I would definitely make this collapsable, but this might show the information of the currently selected gene, which we're going to be hiding, or may not be immediately interesting. Reference is something I would put here, for example, I don't think "reference" would be interesting to most people. We could then also put in the different gene IDs here as well as potentially more information. However, this panel might be too complicated or too general. This is something that would be interesting in other widgets as well. For instance, if I go through some pipeline and identify differentially expressed genes, I might also be interested in the function of individual genes, with links to gene cards from NCBI or something similar. This would require more thought, and should be left out of the first version of the improved widget.

After thinking about this a bit more, the key things are to be able to search for genes by gene short name, Entrez ID, Ensembl ID, in addition to filtering by cell-type. Filtering by functional might also be useful. So the search box should be responsible for all this. For the time being, I think it would be better to remove at least the "reference" and "Entrez id" fields. I'm a bit unsure of what to do with the "function" column. So the layout might be something like
```
Cell type 1
    Gene 1 | functional description
    Gene 2 | functional description
Cell type 2
    Gene 3 | functional description
    Gene 2 | functional description
```

**Comment by PrimozGodec** [comment]
I agree with you the pannel should be a good thing to have. Maybe it can be similar to one in Datasets widget (so at the bottom of the widget). Also, grouping based on combo box should not be too hard to implements
