### ISSUE TITLE
OWHomologs: needs a new icon

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-bioinformatics#181]
As a temporary solution, we used the icon from Genes widget. Before the next release, we should use a different icon for homologs widget. 

<img width="216" alt="Screenshot 2019-08-08 at 09 30 50" src="https://user-images.githubusercontent.com/15876321/62683734-77b8c280-b9bf-11e9-887c-7a39ac754c01.png">

**Comment by ajdapretnar** [comment]
@larazupan @BlazZupan Could we ask for one?

**Comment by BlazZupan** [comment]
@larazupan is working on this one.

**Comment by JakaKokosar** [comment]
Thanks!
