### ISSUE TITLE
Databases Update

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#20]
In case of preliminary annotation data, it would be great to load annotations from local files. 

##### Expected behavior

Include "Load from local file ..." button in the same row as "Update all" and other buttons, but push it all the way to the right. Enable loading GO and KEGG annotations for a start. Annotation file should include all other necessary information, like data source name.

**Comment by JakaKokosar** [comment]
Supported in version 3.0.6
