### ISSUE TITLE
Public datasets

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-bioinformatics#249]
Since the widget will be a part of the bioinformatics add-on, we think that there should be some data that will be publicly available. Otherwise, the widget will be unusable to anyone else. If this is not possible, we should consider a new add-on with Genialis related widgets.

@mstajdohar

**Comment by mstajdohar** [comment]
Genialis Expressions host public data too. See examples in ReSDK documentation, chapter [Getting Started](https://resdk.readthedocs.io/en/latest/start.html#query-data). 

```
import resdk

# Create a Resolwe object to interact with the server and login
res = resdk.Resolwe(url='https://app.genialis.com')

# Enable verbose logging to standard output
resdk.start_logging()

# All paired-end fastq objects
res.data.filter(type='data:reads:fastq:paired')
```

**Comment by mstajdohar** [comment]
@jkokosar or @mzganec can direct you to interesting public collections.
