### ISSUE TITLE
Gene Set Enrichment Widget does not Update When Input Changes

### ISSUE THREAD

**Issue by DLWheeler** [biolab/orange3-bioinformatics#275]
**Describe the bug**
The Gene Set Enrichment widget operates normally on its first input. Ontologies can be selected and the table of term enrichments is updated.  However, the widget does not produce output when a term is selected and it does not update the enrichment table if the input changes.

**To Reproduce**
Workflow: File Input (Brown-selected.tab) -> Gene Info (S. cerevisiae)->Select Rows->Gene Set Enrichment 

Select e.g. "Proteas" in the 'function' category within Select Rows and add the Gene Set Enrichment widget . The widget generates the expected term enrichment table.

Now, change the 'function' to 'Resp' in Select Rows.  The Gene Enrichment widget does not receive the input (red dot appears) and the widget continues to operate on the original data that is no longer on the input.  Add and new Gene Set Enrichment widget and it will operate on the new data until the input changes again.  

Although the widget generates enrichment tables for the first input, it never generates output when selections are made in the table.

**Expected behavior**
I expect the widget to generate a new table every time the input changes and I expect the genes included in any selections I make in the enrichment table to be output via the widget's output channel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave or Catalina 
 - Python Version: [3.8 or 3.7]
 - Orange Version [3.25, 3.26, 3.27]
 - Add-on Version [4.1]

**Additional context**
The bug appeared when I updated to version 4.1 of the bioinformatics add-on

**Comment by JakaKokosar** [comment]
Thank you for submitting. I will look into it :)

**Comment by DLWheeler** [comment]
Just upgraded to 4.2 and all is working perfectly again.  This a very flexible and well-designed widget--I use it quite a bit. Thanks!
