### ISSUE TITLE
GO Browser widget should present itself upon insertion on the canvas

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#3]
##### Expected behavior
GO Browser should present its icon as soon as the widget is introduced to canvas.

##### Actual behavior
Choose some data set from GEO Data Sets, draw a connection, choose GO Browser. The widget takes a while to appear and display progress.

**Comment by JakaKokosar** [comment]
I've included changes made by ales in https://github.com/biolab/orange-bio/commit/4e1a50f2
