### ISSUE TITLE
Genialis Expressions widget should be updated to account for the breaking changes in ReSDK

### ISSUE THREAD

**Issue by mstajdohar** [biolab/orange3-bioinformatics#310]
Change `import resdk` to `import resdk.tables`
Change `coll_table = resdk.tables.CollectionTables` to `coll_table = resdk.tables.RNATables`

Discuss with @robertcv and @JureZmrzlikar if there are more edge cases.

**Comment by mstajdohar** [comment]
cc @JakaKokosar

**Comment by JureZmrzlikar** [comment]
I think the breaking changes are (already) well descried in #304

**Comment by JakaKokosar** [comment]
I have this on my mind. I didn't find time to work on this, but I will look into it soon, hopefully as soon as next week.

**Comment by uksurd88** [comment]
Any update on this? Expressions plugin can't load a collection because of the abovementioned change. Workaround is to install the bioinformatics add-on from source but the `.dmg` file is not updated.

**Comment by JakaKokosar** [comment]
Fixedin #311 and will be included in the next release.
