### ISSUE TITLE
Differential Expression Widget generates a blank output and error message

### ISSUE THREAD

**Issue by IaelWM** [biolab/orange3-bioinformatics#334]
**Describe the bug**
I'm trying to analyse a gene set and find which are differentially expressed between two sample sets, using the differential expression widget from the bioinformatics add-on v 4.7.1. The analysis works fine however when I try to click the "commit" button  a window pops up with the message below and the data table widget with the output is blank
 '''Error encountered in widget **Differential Expression**: 

Traceback (most recent call last):
File: "D:\OrangeStat\lib\site-packages\orangewidget\gui.py", line 2009, in do_commit
commit ( )
File " D:\OrangeStat\lib\site-
packages\orangecontrib\bioinformatics\widgets\OWDifferentialExperission.py" line 1334, in commit
gene_ids = self.data.attributes [GENE_ID_ATTRIBUTES]
KeyError: 'gene_id_attribute'
'''

**Expected behavior**
I expected a data table with the selected genes

**Screenshots**
<img width="960" alt="Captura de tela 2023-07-04 131424" src="https://github.com/biolab/orange3-bioinformatics/assets/43472687/0d67885e-9260-4761-b777-96326620b110">
<img width="960" alt="Captura de tela 2023-07-04 131514" src="https://github.com/biolab/orange3-bioinformatics/assets/43472687/c83a1e02-d368-4b1c-ac85-bd8367c1d1c8">
<img width="960" alt="Captura de tela 2023-07-04 131545" src="https://github.com/biolab/orange3-bioinformatics/assets/43472687/af0a19a0-cd74-4687-8885-5d83ee1fd4e6">
<img width="960" alt="Captura de tela 2023-07-04 131818" src="https://github.com/biolab/orange3-bioinformatics/assets/43472687/a1b729b7-d6cf-476c-a9c4-018133d7a378">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Orange Version 3.35
 - Add-on Version 4.7.1

**Comment by JakaKokosar** [comment]
Thank you for reporting. I will look into it.

**Comment by frankyates06** [comment]
I did not find the solution to this bug: could you please tell me where to find it? 
best (and I apologize, I am a newbie)

**Comment by JakaKokosar** [comment]
@frankyates06 I'm working on it ATM. Will keep you posted.

**Comment by JakaKokosar** [comment]
@frankyates06 and @IaelWM try updating the add-on on 4.8.1.
