### ISSUE TITLE
Gene Name Matcher: add id even when Gene ID present in input data

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#49]
##### Expected behavior

The widget should output column (or attribute of an attribute) with the ID of the gene even if an object (column, or attribute's attribute) with the name "Gene ID" already exists. In this case, construct the name "Gene ID (1)" or "Gene ID (i)", where i is an integer and "Gene ID (i)" is the first occurrence of this name with lowest i that does not exist yet. Do this only if new ID's are different from the old ones.

##### Actual behavior

When "Gene ID" exists, the widget does not add gene IDs.

**Comment by JakaKokosar** [comment]
@BlazZupan  instead of going through all this hassle shouldn't we just use 'Entrez Gene ID' instead of just 'Gene ID'. With this solution we are more specific about what these IDs are and from which database. 

Thoughts?
