### ISSUE TITLE
Gene Info defaults

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#7]
Sort organisms in Gene Info alphabetically. Now they are not sorted and it is hard to find the right organism. Also, before we implement a functionality that would guess the "right" organism, make Homo sapiens a default organism.

Replace "Use attribute names" in the GUI with "Use column names".

**Comment by JakaKokosar** [comment]
Included in: https://github.com/biolab/orange3-bioinformatics/commit/e6467702958adc3cc2a00761e22fc28bd0cd191d
