### ISSUE TITLE
Databases Update: freezes on Download all

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-bioinformatics#88]
##### Bioinformatics version

3.2.0

##### Orange version

3.17.dev

##### Expected behavior
Database Updates downloads selected dataset.

##### Actual behavior
Database Updates downloads all cached datasets.

##### Steps to reproduce the behavior
Database Updates. Deselect all the pre-selected datasets. Then select only one (say, the smallest). Upon pressing Download all, old datasets get selected and the download begins. I think intuitively (and judging by documentation), only the selected datasets should be downloaded.

##### Additional info (worksheets, data, screenshots, ...)
Download is very slow, perhaps since all datasets get downloaded.
Also, I cannot use Cancel button - it doesn't work.

**Comment by JakaKokosar** [comment]
@ajdapretnar 

So the documentation is quite old and there were some changes. Every select or deselect action downloads or removes your data. When you click Download all, every dataset that is not already selected gets downloaded. Cancel button should stop this process (at least for me, can you check again).

**Comment by JakaKokosar** [comment]
When Download all process starts only the list area gets disabled, the widget should stay responsive.

**Comment by JakaKokosar** [comment]
@ajdapretnar can we close this?

**Comment by ajdapretnar** [comment]
Yes.
