### ISSUE TITLE
Gene Sets: output class and meta data

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#9]
##### Expected behavior
Gene Sets should output selected genes along with any metadata and class information.

##### Actual behavior
Class information and metadata is not on the output if genes are in the columns.

**Comment by JakaKokosar** [comment]
Can't reproduce this. Widget sets all metadata and class variables to the output.

Can we close this?

**Comment by JakaKokosar** [comment]
Closing. Reopen if the problem persists.
