### ISSUE TITLE
partial bioinformatics add-on installation

### ISSUE THREAD

**Issue by guikool** [biolab/orange3-bioinformatics#90]
##### Bioinformatics version
3.2

##### Orange version
3.16

##### Expected behavior
Hi,
After installation on bioinformatics add-on through GUI interface I've obtained only nine widgets Databases update, GEO, Dicty, Gene Name, Differential Expression, GO brow, KEGG path, Gen Set enrich and cluster analysis)
I uninstall it and use orange commande prompt. It ask for cython installation. I've done it and reinstall through commad prompt without any errors.

However, the problem is still there...

Thanks for your Help

Guillaume.

**Comment by JakaKokosar** [comment]
Hi @guikool,

this version of bioinformatics add-on does not include all of the widgets that can be found in the legacy [add-on](https://github.com/biolab/orange-bio), which is not supported for quite some time now.

You can install it by running _pip install Orange-Bioinformatics_. If you are unfamiliar with Python PyPI package manager, please report back. Though I must warn you, using unsupported add-on may result in less than optimal user experience.

If I may ask, which widgets are missing for you?

**Comment by guikool** [comment]
Thanks for your  quick reply
Indeed I was really interested using volcano-plot and Quality Control, your solution works perfectly :-) everything is at its own place.
Issue solved!
For the record, I'm dealing with metabolomic data and try to build my own workflows using orange widgets. I 've discovered the soft last week and its amazing.
Congrats and go on!!
