### ISSUE TITLE
GeneNameMatcher: look for gene IDs in attributes-of-attributes

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-bioinformatics#93]
Some protocols output .mtx files that can contain gene ID in attributes-of-attributes.
Any chances Gene Matcher could look there too?

See example file: [aplysia_cAMP_sample.pkl.gz](https://github.com/biolab/orange3-bioinformatics/files/2418326/aplysia_cAMP_sample.pkl.gz)

**Comment by JakaKokosar** [comment]
@mstrazar, is this still relevant? We discussed this and if I remember correctly, the problem was elsewhere, right?

If we want to support this feature, we would need to rethink the structure of the widget. What do you think?

**Comment by mstrazar** [comment]
This issue can be closed, we fixed Merge Data instead.
