### ISSUE TITLE
OWClusterAnalysis: output results in a Table;

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-bioinformatics#98]
Add another output signal to the Cluster Analysis widget, that outputs results in a tabular form.
The table should have one row per result (gene-cluster pair) and all the relevant variables and metadata.

Add another output signal, which is similar, but lists GO terms per cluster in the same way.

Example results:
![owca](https://user-images.githubusercontent.com/5073833/46962361-3c04e300-d0a3-11e8-8854-3b26b0c938d5.png)

Example output:
![table](https://user-images.githubusercontent.com/5073833/46962365-3d361000-d0a3-11e8-900a-854be08e4a4b.png)

**Comment by BlazZupan** [comment]
Name the signals as: Gene Scores, Gene Set Scores
